export const themes = {
  light: {
    name: "Light",
    type: "included",
    price: 0,
    locked: false,
    description: "Clean and simple.",
    colors: {
      background: "#F7FAFC",
     surface: "#FFFDF8",
    surfaceAlt: "#F1EBDD",
      text: "#1A202C",
      muted: "#718096",
      primary: "#4F46E5",
      primaryText: "#FFFFFF",
      success: "#22C55E",
      danger: "#EF4444",
      border: "#E8DDCA",
      tabBar: "#FFFFFF",
    },
  },

  dark: {
    name: "Dark",
    type: "included",
    price: 0,
    locked: false,
    description: "Easy on the eyes.",
    colors: {
      background: "#0F172A",
      surface: "#1E293B",
      surfaceAlt: "#334155",
      text: "#F8FAFC",
      muted: "#94A3B8",
      primary: "#818CF8",
      primaryText: "#FFFFFF",
      success: "#4ADE80",
      danger: "#F87171",
      border: "#334155",
      tabBar: "#1E293B",
    },
  },

  nature: {
    name: "Nature",
    type: "included",
    price: 0,
    locked: false,
    description: "Calm greens and soft focus.",
    colors: {
      background: "#F0FDF4",
      surface: "#FFFFFF",
      surfaceAlt: "#DCFCE7",
      text: "#14532D",
      muted: "#4B8063",
      primary: "#16A34A",
      primaryText: "#FFFFFF",
      success: "#22C55E",
      danger: "#DC2626",
      border: "#BBF7D0",
      tabBar: "#FFFFFF",
    },
  },

  focus: {
    name: "Focus",
    type: "included",
    price: 0,
    locked: false,
    description: "Minimal and distraction-free.",
    colors: {
      background: "#F5F5F4",
      surface: "#FFFFFF",
      surfaceAlt: "#E7E5E4",
      text: "#1C1917",
      muted: "#78716C",
      primary: "#44403C",
      primaryText: "#FFFFFF",
      success: "#57534E",
      danger: "#991B1B",
      border: "#D6D3D1",
      tabBar: "#FFFFFF",
    },
  },

  sunset: {
    name: "Sunset",
    type: "store",
    price: 500,
    locked: true,
    description: "Warm oranges and soft evening tones.",
    colors: {
      background: "#FFF7ED",
      surface: "#FFFFFF",
      surfaceAlt: "#FED7AA",
      text: "#431407",
      muted: "#9A3412",
      primary: "#F97316",
      primaryText: "#FFFFFF",
      success: "#22C55E",
      danger: "#DC2626",
      border: "#FDBA74",
      tabBar: "#FFFFFF",
    },
  },

  ocean: {
    name: "Ocean",
    type: "store",
    price: 750,
    locked: true,
    description: "Cool blues for a calmer day.",
    colors: {
      background: "#EFF6FF",
      surface: "#FFFFFF",
      surfaceAlt: "#DBEAFE",
      text: "#0F172A",
      muted: "#2563EB",
      primary: "#0284C7",
      primaryText: "#FFFFFF",
      success: "#14B8A6",
      danger: "#E11D48",
      border: "#BFDBFE",
      tabBar: "#FFFFFF",
    },
  },

  coffee: {
    name: "Coffee Shop",
    type: "store",
    price: 1000,
    locked: true,
    description: "Warm, cozy, and grounded.",
    colors: {
      background: "#FAF3E7",
      surface: "#FFFaf2",
      surfaceAlt: "#E7D3B5",
      text: "#2B1A10",
      muted: "#7C5E43",
      primary: "#8B5E34",
      primaryText: "#FFFFFF",
      success: "#6B8E23",
      danger: "#B91C1C",
      border: "#D6B98C",
      tabBar: "#FFFaf2",
    },
  },
  forestNight: {
    name: "Forest Night",
    type: "achievement",
   price: 0,
    locked: true,
    unlockAchievement: "streak-7",
   description: "Unlocked by reaching a 7-day streak.",
   colors: {
      background: "#071A12",
      surface: "#10291D",
      surfaceAlt: "#173A2A",
      text: "#ECFDF5",
     muted: "#A7F3D0",
      primary: "#34D399",
     primaryText: "#052E1A",
     success: "#22C55E",
     danger: "#F87171",
     border: "#245B40",
     tabBar: "#10291D",
  },
},
};

export const DEFAULT_THEME = "light";

export const INCLUDED_THEMES = Object.keys(themes).filter(
  (key) => themes[key].type === "included"
);