export const themes = {
  light: {
    name: "Daylight",
    type: "included",
    rarity: "common",
    price: 0,
    locked: false,
    description: "Clean, bright, and easy to read.",
    tagline: "Best for everyday use",
    mood: "balanced",
    statusBar: "dark",
    glow: "#22C7DE",
    gradient: ["#F8FAFC", "#EAF4FF", "#22C7DE"],
    colors: {
      background: "#F4F7FB",
      surface: "#FFFFFF",
      surfaceAlt: "#EEF3F8",
      surfaceElevated: "#FFFFFF",
      surfaceGlow: "rgba(34, 199, 222, 0.14)",

      text: "#122033",
      textSecondary: "#56657A",
      textMuted: "#8593A3",
      muted: "#8593A3",

      primary: "#132238",
      accent: "#22C7DE",
      primaryText: "#FFFFFF",

      cyan: "#22C7DE",
      blue: "#2494F2",
      coral: "#FF7E6B",
      gold: "#FFC96B",

      success: "#2EC27E",
      warning: "#F5A524",
      danger: "#EF4444",
      info: "#3B82F6",

      border: "#DCE5EE",
      divider: "#E8EEF5",
      tabBar: "#FFFFFF",
    },
  },

  dark: {
    name: "Midnight Orbit",
    type: "included",
    rarity: "common",
    price: 0,
    locked: false,
    description: "Atmospheric dark mode built around calm momentum.",
    tagline: "Signature dark mode",
    mood: "focused",
    statusBar: "light",
    glow: "#22D3EE",
    gradient: ["#050816", "#0F172A", "#1E1B4B"],
    colors: {
      background: "#050816",
      surface: "#0F172A",
      surfaceAlt: "#172033",
      surfaceElevated: "#172554",
      surfaceGlow: "rgba(34, 211, 238, 0.18)",

      text: "#F8FAFC",
      textSecondary: "#CBD5E1",
      textMuted: "#94A3B8",
      muted: "#94A3B8",

      primary: "#22D3EE",
      accent: "#7C3AED",
      primaryText: "#03151A",

      cyan: "#22D3EE",
      blue: "#60A5FA",
      coral: "#FF7E6B",
      gold: "#FBBF24",

      success: "#34D399",
      warning: "#FBBF24",
      danger: "#FB7185",
      info: "#60A5FA",

      border: "#22304A",
      divider: "#1E293B",
      tabBar: "#0F172A",
    },
  },

  nature: {
    name: "Evergreen",
    type: "included",
    rarity: "common",
    price: 0,
    locked: false,
    description: "Calm greens and soft focus.",
    tagline: "Most calming",
    mood: "calm",
    statusBar: "dark",
    glow: "#16A34A",
    gradient: ["#F0FDF4", "#DCFCE7", "#16A34A"],
    colors: {
      background: "#F0FDF4",
      surface: "#FFFFFF",
      surfaceAlt: "#DCFCE7",
      surfaceElevated: "#FFFFFF",
      surfaceGlow: "rgba(22, 163, 74, 0.14)",

      text: "#14532D",
      textSecondary: "#4B8063",
      textMuted: "#6B987C",
      muted: "#4B8063",

      primary: "#16A34A",
      accent: "#22C55E",
      primaryText: "#FFFFFF",

      cyan: "#14B8A6",
      blue: "#0EA5E9",
      coral: "#F97316",
      gold: "#EAB308",

      success: "#22C55E",
      warning: "#EAB308",
      danger: "#DC2626",
      info: "#0EA5E9",

      border: "#BBF7D0",
      divider: "#D8F5E0",
      tabBar: "#FFFFFF",
    },
  },

  focus: {
    name: "Slate",
    type: "included",
    rarity: "common",
    price: 0,
    locked: false,
    description: "Minimal and distraction-free.",
    tagline: "Best for focus",
    mood: "minimal",
    statusBar: "dark",
    glow: "#44403C",
    gradient: ["#F8FAFC", "#D6D3D1", "#44403C"],
    colors: {
      background: "#F5F5F4",
      surface: "#FFFFFF",
      surfaceAlt: "#E7E5E4",
      surfaceElevated: "#FFFFFF",
      surfaceGlow: "rgba(68, 64, 60, 0.12)",

      text: "#1C1917",
      textSecondary: "#625C57",
      textMuted: "#78716C",
      muted: "#78716C",

      primary: "#44403C",
      accent: "#78716C",
      primaryText: "#FFFFFF",

      cyan: "#0891B2",
      blue: "#2563EB",
      coral: "#EA580C",
      gold: "#CA8A04",

      success: "#57534E",
      warning: "#EAB308",
      danger: "#991B1B",
      info: "#2563EB",

      border: "#D6D3D1",
      divider: "#E7E5E4",
      tabBar: "#FFFFFF",
    },
  },

  amoled: {
    name: "AMOLED",
    type: "store",
    rarity: "rare",
    price: 500,
    locked: true,
    description: "Pure black, high contrast, battery-friendly.",
    tagline: "Best for OLED screens",
    mood: "focused",
    statusBar: "light",
    glow: "#22C55E",
    gradient: ["#000000", "#052E16", "#22C55E"],
    colors: {
      background: "#000000",
      surface: "#080808",
      surfaceAlt: "#141414",
      surfaceElevated: "#1C1C1C",
      surfaceGlow: "rgba(34, 197, 94, 0.16)",

      text: "#FAFAFA",
      textSecondary: "#D4D4D4",
      textMuted: "#A3A3A3",
      muted: "#A3A3A3",

      primary: "#22C55E",
      accent: "#4ADE80",
      primaryText: "#001A0A",

      cyan: "#22D3EE",
      blue: "#60A5FA",
      coral: "#FB7185",
      gold: "#FBBF24",

      success: "#22C55E",
      warning: "#EAB308",
      danger: "#EF4444",
      info: "#60A5FA",

      border: "#262626",
      divider: "#171717",
      tabBar: "#050505",
    },
  },

  ocean: {
    name: "Tidal",
    type: "store",
    rarity: "rare",
    price: 750,
    locked: true,
    description: "Cool blues for a calmer day.",
    tagline: "Cool and focused",
    mood: "calm",
    statusBar: "dark",
    glow: "#0284C7",
    gradient: ["#EFF6FF", "#DBEAFE", "#0284C7"],
    colors: {
      background: "#EFF6FF",
      surface: "#FFFFFF",
      surfaceAlt: "#DBEAFE",
      surfaceElevated: "#FFFFFF",
      surfaceGlow: "rgba(2, 132, 199, 0.14)",

      text: "#0F172A",
      textSecondary: "#1D4ED8",
      textMuted: "#2563EB",
      muted: "#2563EB",

      primary: "#0284C7",
      accent: "#06B6D4",
      primaryText: "#FFFFFF",

      cyan: "#06B6D4",
      blue: "#0284C7",
      coral: "#F97316",
      gold: "#EAB308",

      success: "#14B8A6",
      warning: "#EAB308",
      danger: "#E11D48",
      info: "#0284C7",

      border: "#BFDBFE",
      divider: "#DBEAFE",
      tabBar: "#FFFFFF",
    },
  },

  coffee: {
    name: "Ember",
    type: "store",
    rarity: "epic",
    price: 1000,
    locked: true,
    description: "Warm, cozy, and grounded.",
    tagline: "Cozy productivity",
    mood: "grounded",
    statusBar: "dark",
    glow: "#8B5E34",
    gradient: ["#FAF3E7", "#E7D3B5", "#8B5E34"],
    colors: {
      background: "#FAF3E7",
      surface: "#FFFAF2",
      surfaceAlt: "#E7D3B5",
      surfaceElevated: "#FFFFFF",
      surfaceGlow: "rgba(139, 94, 52, 0.14)",

      text: "#2B1A10",
      textSecondary: "#654B32",
      textMuted: "#7C5E43",
      muted: "#7C5E43",

      primary: "#8B5E34",
      accent: "#C08457",
      primaryText: "#FFFFFF",

      cyan: "#0891B2",
      blue: "#2563EB",
      coral: "#C2410C",
      gold: "#D97706",

      success: "#6B8E23",
      warning: "#EAB308",
      danger: "#B91C1C",
      info: "#2563EB",

      border: "#D6B98C",
      divider: "#E8D8BD",
      tabBar: "#FFFAF2",
    },
  },

  solsticeStore: {
    name: "Solstice",
    type: "store",
    rarity: "epic",
    price: 1250,
    locked: true,
    description: "Warm oranges and soft evening tones.",
    tagline: "Warm evening energy",
    mood: "warm",
    statusBar: "dark",
    glow: "#F97316",
    gradient: ["#FFF7ED", "#FDBA74", "#F97316"],
    colors: {
      background: "#FFF7ED",
      surface: "#FFFFFF",
      surfaceAlt: "#FED7AA",
      surfaceElevated: "#FFFFFF",
      surfaceGlow: "rgba(249, 115, 22, 0.14)",

      text: "#431407",
      textSecondary: "#7C2D12",
      textMuted: "#9A3412",
      muted: "#9A3412",

      primary: "#F97316",
      accent: "#FB923C",
      primaryText: "#FFFFFF",

      cyan: "#0891B2",
      blue: "#2563EB",
      coral: "#F97316",
      gold: "#EAB308",

      success: "#22C55E",
      warning: "#EAB308",
      danger: "#DC2626",
      info: "#2563EB",

      border: "#FDBA74",
      divider: "#FED7AA",
      tabBar: "#FFFFFF",
    },
  },

  forestNight: {
    name: "Forest Night",
    type: "achievement",
    rarity: "rare",
    price: 0,
    locked: true,
    unlockAchievement: "streak-7",
    description: "Unlocked by reaching a 7-day streak.",
    tagline: "Earned by consistency",
    mood: "calm",
    statusBar: "light",
    glow: "#34D399",
    gradient: ["#071A12", "#10291D", "#34D399"],
    colors: {
      background: "#071A12",
      surface: "#10291D",
      surfaceAlt: "#173A2A",
      surfaceElevated: "#1F4A35",
      surfaceGlow: "rgba(52, 211, 153, 0.16)",

      text: "#ECFDF5",
      textSecondary: "#A7F3D0",
      textMuted: "#6EE7B7",
      muted: "#A7F3D0",

      primary: "#34D399",
      accent: "#10B981",
      primaryText: "#052E1A",

      cyan: "#2DD4BF",
      blue: "#60A5FA",
      coral: "#FB7185",
      gold: "#FBBF24",

      success: "#22C55E",
      warning: "#EAB308",
      danger: "#F87171",
      info: "#60A5FA",

      border: "#245B40",
      divider: "#173A2A",
      tabBar: "#10291D",
    },
  },

  aurora: {
    name: "Aurora",
    type: "achievement",
    rarity: "epic",
    price: 0,
    locked: true,
    unlockAchievement: "coins-500",
    description: "Unlocked by earning 500 total coins.",
    tagline: "Earned by progress",
    mood: "electric",
    statusBar: "light",
    glow: "#06B6D4",
    gradient: ["#0B1020", "#7C3AED", "#06B6D4"],
    colors: {
      background: "#0B1020",
      surface: "#141B34",
      surfaceAlt: "#1C2547",
      surfaceElevated: "#25305C",
      surfaceGlow: "rgba(6, 182, 212, 0.18)",

      text: "#F3F7FF",
      textSecondary: "#C7D2FE",
      textMuted: "#A5B4FC",
      muted: "#A5B4FC",

      primary: "#7C3AED",
      accent: "#06B6D4",
      primaryText: "#FFFFFF",

      cyan: "#06B6D4",
      blue: "#60A5FA",
      coral: "#EC4899",
      gold: "#FBBF24",

      success: "#22C55E",
      warning: "#EAB308",
      danger: "#F87171",
      info: "#60A5FA",

      border: "#2E3A67",
      divider: "#1C2547",
      tabBar: "#141B34",
    },
  },

  solstice: {
    name: "Solstice Crown",
    type: "achievement",
    rarity: "epic",
    price: 0,
    locked: true,
    unlockAchievement: "tasks-50",
    description: "Unlocked by completing 50 tasks.",
    tagline: "Earned by execution",
    mood: "warm",
    statusBar: "dark",
    glow: "#F97316",
    gradient: ["#FFF4E8", "#F97316", "#E11D48"],
    colors: {
      background: "#FFF4E8",
      surface: "#FFFFFF",
      surfaceAlt: "#FFE4C7",
      surfaceElevated: "#FFFFFF",
      surfaceGlow: "rgba(249, 115, 22, 0.14)",

      text: "#5A2D0C",
      textSecondary: "#824A1D",
      textMuted: "#9A5B2A",
      muted: "#9A5B2A",

      primary: "#F97316",
      accent: "#E11D48",
      primaryText: "#FFFFFF",

      cyan: "#0891B2",
      blue: "#2563EB",
      coral: "#F97316",
      gold: "#EAB308",

      success: "#22C55E",
      warning: "#EAB308",
      danger: "#DC2626",
      info: "#2563EB",

      border: "#F4C38D",
      divider: "#FFE4C7",
      tabBar: "#FFFFFF",
    },
  },

  midnightGold: {
    name: "Obsidian Gold",
    type: "achievement",
    rarity: "legendary",
    price: 0,
    locked: true,
    unlockAchievement: "streak-30",
    description: "Unlocked by reaching a 30-day streak.",
    tagline: "Legendary streak reward",
    mood: "prestige",
    statusBar: "light",
    glow: "#EAB308",
    gradient: ["#09090B", "#18181B", "#EAB308"],
    colors: {
      background: "#09090B",
      surface: "#18181B",
      surfaceAlt: "#27272A",
      surfaceElevated: "#3F3F46",
      surfaceGlow: "rgba(234, 179, 8, 0.18)",

      text: "#FAFAFA",
      textSecondary: "#E4E4E7",
      textMuted: "#D4D4D8",
      muted: "#D4D4D8",

      primary: "#EAB308",
      accent: "#FACC15",
      primaryText: "#18181B",

      cyan: "#22D3EE",
      blue: "#60A5FA",
      coral: "#FB7185",
      gold: "#EAB308",

      success: "#22C55E",
      warning: "#EAB308",
      danger: "#F87171",
      info: "#60A5FA",

      border: "#3F3F46",
      divider: "#27272A",
      tabBar: "#18181B",
    },
  },

  oceanBreeze: {
    name: "Ocean Breeze",
    type: "achievement",
    rarity: "rare",
    price: 0,
    locked: true,
    unlockAchievement: "habits-25",
    description: "Unlocked by completing 25 habits.",
    tagline: "Earned by rhythm",
    mood: "calm",
    statusBar: "dark",
    glow: "#06B6D4",
    gradient: ["#F0FDFF", "#DDF7FA", "#06B6D4"],
    colors: {
      background: "#F0FDFF",
      surface: "#FFFFFF",
      surfaceAlt: "#DDF7FA",
      surfaceElevated: "#FFFFFF",
      surfaceGlow: "rgba(6, 182, 212, 0.14)",

      text: "#164E63",
      textSecondary: "#0F766E",
      textMuted: "#0891B2",
      muted: "#0F766E",

      primary: "#06B6D4",
      accent: "#0891B2",
      primaryText: "#FFFFFF",

      cyan: "#06B6D4",
      blue: "#0284C7",
      coral: "#F97316",
      gold: "#EAB308",

      success: "#10B981",
      warning: "#EAB308",
      danger: "#EF4444",
      info: "#0284C7",

      border: "#B6EAF2",
      divider: "#DDF7FA",
      tabBar: "#FFFFFF",
    },
  },

  roseGarden: {
    name: "Rose Garden",
    type: "achievement",
    rarity: "rare",
    price: 0,
    locked: true,
    unlockAchievement: "quests-10",
    description: "Unlocked by completing 10 quests.",
    tagline: "Earned by adventure",
    mood: "warm",
    statusBar: "dark",
    glow: "#E11D48",
    gradient: ["#FFF1F2", "#FFE4E6", "#E11D48"],
    colors: {
      background: "#FFF1F2",
      surface: "#FFFFFF",
      surfaceAlt: "#FFE4E6",
      surfaceElevated: "#FFFFFF",
      surfaceGlow: "rgba(225, 29, 72, 0.14)",

      text: "#881337",
      textSecondary: "#9F1239",
      textMuted: "#BE185D",
      muted: "#BE185D",

      primary: "#E11D48",
      accent: "#F43F5E",
      primaryText: "#FFFFFF",

      cyan: "#0891B2",
      blue: "#2563EB",
      coral: "#F43F5E",
      gold: "#EAB308",

      success: "#22C55E",
      warning: "#EAB308",
      danger: "#DC2626",
      info: "#2563EB",

      border: "#FBCDD3",
      divider: "#FFE4E6",
      tabBar: "#FFFFFF",
    },
  },

  comet: {
    name: "Comet",
    type: "level",
    rarity: "rare",
    price: 0,
    locked: true,
    unlockLevel: 3,
    description: "Unlocked at Orbit Level 3.",
    tagline: "Fast momentum",
    mood: "electric",
    statusBar: "light",
    glow: "#22D3EE",
    gradient: ["#06131F", "#0F1E2D", "#22D3EE"],
    colors: {
      background: "#06131F",
      surface: "#0F1E2D",
      surfaceAlt: "#183041",
      surfaceElevated: "#244459",
      surfaceGlow: "rgba(34, 211, 238, 0.18)",

      text: "#E0F7FF",
      textSecondary: "#BAE6FD",
      textMuted: "#7DD3FC",
      muted: "#7DD3FC",

      primary: "#22D3EE",
      accent: "#38BDF8",
      primaryText: "#06202A",

      cyan: "#22D3EE",
      blue: "#60A5FA",
      coral: "#FB7185",
      gold: "#FBBF24",

      success: "#22C55E",
      warning: "#EAB308",
      danger: "#F87171",
      info: "#60A5FA",

      border: "#244459",
      divider: "#183041",
      tabBar: "#0F1E2D",
    },
  },

  nebula: {
    name: "Nebula",
    type: "level",
    rarity: "epic",
    price: 0,
    locked: true,
    unlockLevel: 5,
    description: "Unlocked at Orbit Level 5.",
    tagline: "Cosmic energy",
    mood: "cosmic",
    statusBar: "light",
    glow: "#A855F7",
    gradient: ["#140B2D", "#7C3AED", "#EC4899"],
    colors: {
      background: "#140B2D",
      surface: "#1F1147",
      surfaceAlt: "#2B1761",
      surfaceElevated: "#3B2180",
      surfaceGlow: "rgba(168, 85, 247, 0.2)",

      text: "#F8F5FF",
      textSecondary: "#DDD6FE",
      textMuted: "#C4B5FD",
      muted: "#C4B5FD",

      primary: "#A855F7",
      accent: "#EC4899",
      primaryText: "#FFFFFF",

      cyan: "#22D3EE",
      blue: "#60A5FA",
      coral: "#EC4899",
      gold: "#FBBF24",

      success: "#22C55E",
      warning: "#EAB308",
      danger: "#FB7185",
      info: "#60A5FA",

      border: "#3E2A72",
      divider: "#2B1761",
      tabBar: "#1F1147",
    },
  },

  eclipse: {
    name: "Eclipse",
    type: "level",
    rarity: "legendary",
    price: 0,
    locked: true,
    unlockLevel: 10,
    description: "Unlocked at Orbit Level 10.",
    tagline: "Dark prestige",
    mood: "prestige",
    statusBar: "light",
    glow: "#2563EB",
    gradient: ["#020617", "#0F172A", "#2563EB"],
    colors: {
      background: "#020617",
      surface: "#0F172A",
      surfaceAlt: "#172554",
      surfaceElevated: "#1E3A8A",
      surfaceGlow: "rgba(37, 99, 235, 0.2)",

      text: "#F8FAFC",
      textSecondary: "#BFDBFE",
      textMuted: "#93C5FD",
      muted: "#93C5FD",

      primary: "#2563EB",
      accent: "#60A5FA",
      primaryText: "#FFFFFF",

      cyan: "#22D3EE",
      blue: "#60A5FA",
      coral: "#FB7185",
      gold: "#FBBF24",

      success: "#22C55E",
      warning: "#EAB308",
      danger: "#F87171",
      info: "#60A5FA",

      border: "#1E3A8A",
      divider: "#172554",
      tabBar: "#0F172A",
    },
  },

  cosmicGold: {
    name: "Cosmic Gold",
    type: "level",
    rarity: "legendary",
    price: 0,
    locked: true,
    unlockLevel: 15,
    description: "Unlocked at Orbit Level 15.",
    tagline: "Elite orbit",
    mood: "prestige",
    statusBar: "light",
    glow: "#EAB308",
    gradient: ["#09090B", "#18181B", "#EAB308"],
    colors: {
      background: "#09090B",
      surface: "#18181B",
      surfaceAlt: "#27272A",
      surfaceElevated: "#3F3F46",
      surfaceGlow: "rgba(234, 179, 8, 0.2)",

      text: "#FAFAFA",
      textSecondary: "#FEF3C7",
      textMuted: "#FDE68A",
      muted: "#FDE68A",

      primary: "#EAB308",
      accent: "#FACC15",
      primaryText: "#18181B",

      cyan: "#22D3EE",
      blue: "#60A5FA",
      coral: "#FB7185",
      gold: "#EAB308",

      success: "#22C55E",
      warning: "#EAB308",
      danger: "#F87171",
      info: "#60A5FA",

      border: "#3F3F46",
      divider: "#27272A",
      tabBar: "#18181B",
    },
  },
};

export const DEFAULT_THEME = "light";

export const INCLUDED_THEMES = Object.keys(themes).filter(
  (key) => themes[key].type === "included"
);

export const STORE_THEMES = Object.keys(themes).filter(
  (key) => themes[key].type === "store"
);

export const ACHIEVEMENT_THEMES = Object.keys(themes).filter(
  (key) => themes[key].type === "achievement"
);

export const LEVEL_THEMES = Object.keys(themes).filter(
  (key) => themes[key].type === "level"
);