export const themes = {
  light: {
    name: "Daylight",
    type: "included",
    rarity: "common",
    price: 0,
    locked: false,
    description: "Clean, bright, and easy to read.",
    tagline: "Best for everyday use",
    gradient: ["#F7FAFC", "#4F46E5"],
    colors: {
      background: "#F7FAFC",
      surface: "#FFFDF8",
      surfaceAlt: "#F1EBDD",
      text: "#1A202C",
      muted: "#718096",
      primary: "#4F46E5",
      primaryText: "#FFFFFF",
      success: "#22C55E",
      danger: "#EF4444",
      border: "#E8DDCA",
      tabBar: "#FFFFFF",
      warning: "#EAB308",
    },
  },

  dark: {
    name: "Midnight",
    type: "included",
    rarity: "common",
    price: 0,
    locked: false,
    description: "Comfortable dark mode for night use.",
    tagline: "Low light friendly",
    gradient: ["#0F172A", "#818CF8"],
    colors: {
      background: "#0F172A",
      surface: "#1E293B",
      surfaceAlt: "#334155",
      text: "#F8FAFC",
      muted: "#94A3B8",
      primary: "#818CF8",
      primaryText: "#FFFFFF",
      success: "#4ADE80",
      danger: "#F87171",
      border: "#334155",
      tabBar: "#1E293B",
      warning: "#EAB308",
    },
  },

  nature: {
    name: "Evergreen",
    type: "included",
    rarity: "common",
    price: 0,
    locked: false,
    description: "Calm greens and soft focus.",
    tagline: "Most calming",
    gradient: ["#F0FDF4", "#16A34A"],
    colors: {
      background: "#F0FDF4",
      surface: "#FFFFFF",
      surfaceAlt: "#DCFCE7",
      text: "#14532D",
      muted: "#4B8063",
      primary: "#16A34A",
      primaryText: "#FFFFFF",
      success: "#22C55E",
      danger: "#DC2626",
      border: "#BBF7D0",
      tabBar: "#FFFFFF",
      warning: "#EAB308",
    },
  },

  focus: {
    name: "Slate",
    type: "included",
    rarity: "common",
    price: 0,
    locked: false,
    description: "Minimal and distraction-free.",
    tagline: "Best for focus",
    gradient: ["#F5F5F4", "#44403C"],
    colors: {
      background: "#F5F5F4",
      surface: "#FFFFFF",
      surfaceAlt: "#E7E5E4",
      text: "#1C1917",
      muted: "#78716C",
      primary: "#44403C",
      primaryText: "#FFFFFF",
      success: "#57534E",
      danger: "#991B1B",
      border: "#D6D3D1",
      tabBar: "#FFFFFF",
      warning: "#EAB308",
    },
  },

  amoled: {
    name: "AMOLED",
    type: "store",
    rarity: "rare",
    price: 500,
    locked: true,
    description: "Pure black, high contrast, battery-friendly.",
    tagline: "Best for OLED screens",
    gradient: ["#000000", "#22C55E"],
    colors: {
      background: "#000000",
      surface: "#0A0A0A",
      surfaceAlt: "#151515",
      text: "#FAFAFA",
      muted: "#A3A3A3",
      primary: "#22C55E",
      primaryText: "#001A0A",
      success: "#22C55E",
      danger: "#EF4444",
      border: "#262626",
      tabBar: "#050505",
      warning: "#EAB308",
    },
  },

  ocean: {
    name: "Tidal",
    type: "store",
    rarity: "rare",
    price: 750,
    locked: true,
    description: "Cool blues for a calmer day.",
    tagline: "Cool and focused",
    gradient: ["#EFF6FF", "#0284C7"],
    colors: {
      background: "#EFF6FF",
      surface: "#FFFFFF",
      surfaceAlt: "#DBEAFE",
      text: "#0F172A",
      muted: "#2563EB",
      primary: "#0284C7",
      primaryText: "#FFFFFF",
      success: "#14B8A6",
      danger: "#E11D48",
      border: "#BFDBFE",
      tabBar: "#FFFFFF",
      warning: "#EAB308",
    },
  },

  coffee: {
    name: "Ember",
    type: "store",
    rarity: "epic",
    price: 1000,
    locked: true,
    description: "Warm, cozy, and grounded.",
    tagline: "Cozy productivity",
    gradient: ["#FAF3E7", "#8B5E34"],
    colors: {
      background: "#FAF3E7",
      surface: "#FFFAF2",
      surfaceAlt: "#E7D3B5",
      text: "#2B1A10",
      muted: "#7C5E43",
      primary: "#8B5E34",
      primaryText: "#FFFFFF",
      success: "#6B8E23",
      danger: "#B91C1C",
      border: "#D6B98C",
      tabBar: "#FFFAF2",
      warning: "#EAB308",
    },
  },

  solsticeStore: {
    name: "Solstice",
    type: "store",
    rarity: "epic",
    price: 1250,
    locked: true,
    description: "Warm oranges and soft evening tones.",
    tagline: "Warm evening energy",
    gradient: ["#FFF7ED", "#F97316"],
    colors: {
      background: "#FFF7ED",
      surface: "#FFFFFF",
      surfaceAlt: "#FED7AA",
      text: "#431407",
      muted: "#9A3412",
      primary: "#F97316",
      primaryText: "#FFFFFF",
      success: "#22C55E",
      danger: "#DC2626",
      border: "#FDBA74",
      tabBar: "#FFFFFF",
      warning: "#EAB308",
    },
  },

  forestNight: {
    name: "Forest Night",
    type: "achievement",
    rarity: "rare",
    price: 0,
    locked: true,
    unlockAchievement: "streak-7",
    description: "Unlocked by reaching a 7-day streak.",
    tagline: "Earned by consistency",
    gradient: ["#071A12", "#34D399"],
    colors: {
      background: "#071A12",
      surface: "#10291D",
      surfaceAlt: "#173A2A",
      text: "#ECFDF5",
      muted: "#A7F3D0",
      primary: "#34D399",
      primaryText: "#052E1A",
      success: "#22C55E",
      danger: "#F87171",
      border: "#245B40",
      tabBar: "#10291D",
      warning: "#EAB308",
    },
  },

  aurora: {
    name: "Aurora",
    type: "achievement",
    rarity: "epic",
    price: 0,
    locked: true,
    unlockAchievement: "coins-500",
    description: "Unlocked by earning 500 total coins.",
    tagline: "Earned by progress",
    gradient: ["#0B1020", "#7C3AED", "#06B6D4"],
    colors: {
      background: "#0B1020",
      surface: "#141B34",
      surfaceAlt: "#1C2547",
      text: "#F3F7FF",
      muted: "#A5B4FC",
      primary: "#7C3AED",
      primaryText: "#FFFFFF",
      success: "#22C55E",
      danger: "#F87171",
      border: "#2E3A67",
      tabBar: "#141B34",
      warning: "#EAB308",
    },
  },

  solstice: {
    name: "Solstice Crown",
    type: "achievement",
    rarity: "epic",
    price: 0,
    locked: true,
    unlockAchievement: "tasks-50",
    description: "Unlocked by completing 50 tasks.",
    tagline: "Earned by execution",
    gradient: ["#FFF4E8", "#F97316", "#E11D48"],
    colors: {
      background: "#FFF4E8",
      surface: "#FFFFFF",
      surfaceAlt: "#FFE4C7",
      text: "#5A2D0C",
      muted: "#9A5B2A",
      primary: "#F97316",
      primaryText: "#FFFFFF",
      success: "#22C55E",
      danger: "#DC2626",
      border: "#F4C38D",
      tabBar: "#FFFFFF",
      warning: "#EAB308",
    },
  },

  midnightGold: {
    name: "Obsidian Gold",
    type: "achievement",
    rarity: "legendary",
    price: 0,
    locked: true,
    unlockAchievement: "streak-30",
    description: "Unlocked by reaching a 30-day streak.",
    tagline: "Legendary streak reward",
    gradient: ["#09090B", "#EAB308"],
    colors: {
      background: "#09090B",
      surface: "#18181B",
      surfaceAlt: "#27272A",
      text: "#FAFAFA",
      muted: "#D4D4D8",
      primary: "#EAB308",
      primaryText: "#18181B",
      success: "#22C55E",
      danger: "#F87171",
      border: "#3F3F46",
      tabBar: "#18181B",
      warning: "#EAB308",
    },
  },

  oceanBreeze: {
    name: "Ocean Breeze",
    type: "achievement",
    rarity: "rare",
    price: 0,
    locked: true,
    unlockAchievement: "habits-25",
    description: "Unlocked by completing 25 habits.",
    tagline: "Earned by rhythm",
    gradient: ["#F0FDFF", "#06B6D4"],
    colors: {
      background: "#F0FDFF",
      surface: "#FFFFFF",
      surfaceAlt: "#DDF7FA",
      text: "#164E63",
      muted: "#0F766E",
      primary: "#06B6D4",
      primaryText: "#FFFFFF",
      success: "#10B981",
      danger: "#EF4444",
      border: "#B6EAF2",
      tabBar: "#FFFFFF",
      warning: "#EAB308",
    },
  },

  roseGarden: {
    name: "Rose Garden",
    type: "achievement",
    rarity: "rare",
    price: 0,
    locked: true,
    unlockAchievement: "quests-10",
    description: "Unlocked by completing 10 quests.",
    tagline: "Earned by adventure",
    gradient: ["#FFF1F2", "#E11D48"],
    colors: {
      background: "#FFF1F2",
      surface: "#FFFFFF",
      surfaceAlt: "#FFE4E6",
      text: "#881337",
      muted: "#BE185D",
      primary: "#E11D48",
      primaryText: "#FFFFFF",
      success: "#22C55E",
      danger: "#DC2626",
      border: "#FBCDD3",
      tabBar: "#FFFFFF",
      warning: "#EAB308",
    },
  },
    comet: {
    name: "Comet",
    type: "level",
    rarity: "rare",
    price: 0,
    locked: true,
    unlockLevel: 3,
    description: "Unlocked at Orbit Level 3.",
    tagline: "Fast momentum",
    gradient: ["#06131F", "#22D3EE"],
    colors: {
      background: "#06131F",
      surface: "#0F1E2D",
      surfaceAlt: "#183041",
      text: "#E0F7FF",
      muted: "#7DD3FC",
      primary: "#22D3EE",
      primaryText: "#06202A",
      success: "#22C55E",
      danger: "#F87171",
      border: "#244459",
      tabBar: "#0F1E2D",
      warning: "#EAB308",
    },
  },

  nebula: {
    name: "Nebula",
    type: "level",
    rarity: "epic",
    price: 0,
    locked: true,
    unlockLevel: 5,
    description: "Unlocked at Orbit Level 5.",
    tagline: "Cosmic energy",
    gradient: ["#140B2D", "#7C3AED", "#EC4899"],
    colors: {
      background: "#140B2D",
      surface: "#1F1147",
      surfaceAlt: "#2B1761",
      text: "#F8F5FF",
      muted: "#C4B5FD",
      primary: "#A855F7",
      primaryText: "#FFFFFF",
      success: "#22C55E",
      danger: "#FB7185",
      border: "#3E2A72",
      tabBar: "#1F1147",
      warning: "#EAB308",
    },
  },

  eclipse: {
    name: "Eclipse",
    type: "level",
    rarity: "legendary",
    price: 0,
    locked: true,
    unlockLevel: 10,
    description: "Unlocked at Orbit Level 10.",
    tagline: "Dark prestige",
    gradient: ["#020617", "#2563EB"],
    colors: {
      background: "#020617",
      surface: "#0F172A",
      surfaceAlt: "#172554",
      text: "#F8FAFC",
      muted: "#93C5FD",
      primary: "#2563EB",
      primaryText: "#FFFFFF",
      success: "#22C55E",
      danger: "#F87171",
      border: "#1E3A8A",
      tabBar: "#0F172A",
      warning: "#EAB308",
    },
  },

  cosmicGold: {
    name: "Cosmic Gold",
    type: "level",
    rarity: "legendary",
    price: 0,
    locked: true,
    unlockLevel: 15,
    description: "Unlocked at Orbit Level 15.",
    tagline: "Elite orbit",
    gradient: ["#09090B", "#EAB308"],
    colors: {
      background: "#09090B",
      surface: "#18181B",
      surfaceAlt: "#27272A",
      text: "#FAFAFA",
      muted: "#FDE68A",
      primary: "#EAB308",
      primaryText: "#18181B",
      success: "#22C55E",
      danger: "#F87171",
      border: "#3F3F46",
      tabBar: "#18181B",
      warning: "#EAB308",
    },
  },
};

export const DEFAULT_THEME = "light";

export const INCLUDED_THEMES = Object.keys(themes).filter(
  (key) => themes[key].type === "included"
);

export const STORE_THEMES = Object.keys(themes).filter(
  (key) => themes[key].type === "store"
);

export const ACHIEVEMENT_THEMES = Object.keys(themes).filter(
  (key) => themes[key].type === "achievement"
);

export const LEVEL_THEMES = Object.keys(themes).filter(
  (key) => themes[key].type === "level"
);