export const TEMPLATE_CATALOG = [
  {
    id: "family",
    name: "Family Orbit",
    short_name: "Family",
    description: "Shared goals, chores, rewards, and family accountability.",
    category: "Home & Family",
    theme_id: "family",
    featured: true,
    premium: false,
    version: 1,
    icon: "home-heart",
    placeholder: "Williams Family",
    starter_summary: ["Family habits", "Shared rewards", "Starter projects", "Milestones", "Parent/child roles"],
    included: {
      habits: ["Daily Reading", "Chores", "Family Dinner"],
      rewards: ["Family Movie Night", "Pizza Night", "Choose Dinner", "Extra Screen Time", "Family Activity Choice"],
      projects: ["Family Routines Setup"],
      milestones: ["First shared habit", "Family consistency", "First reward redeemed"],
      roles: ["Parent", "Child"],
    },
  },
  {
    id: "scout_troop",
    name: "Scout Troop Orbit",
    short_name: "Scout Troop",
    description: "Meetings, campouts, service projects, leadership, and troop accountability.",
    category: "Troops & Clubs",
    theme_id: "scout",
    featured: true,
    premium: false,
    version: 1,
    icon: "tent",
    placeholder: "Troop 123",
    starter_summary: ["Troop habits", "Camp readiness", "Patrol structure", "Troop projects", "Milestones"],
    included: {
      habits: ["Physical Fitness", "Scout Skill Practice", "Daily Scout Spirit"],
      rewards: ["Troop Recognition", "Patrol Pizza Party", "Campout Privilege", "Patrol Choice Activity"],
      projects: ["Troop Launch Plan"],
      milestones: ["First patrol created", "First campout planned", "Troop XP milestones"],
      roles: ["Scoutmaster", "Assistant Scoutmaster", "SPL", "Patrol Leader", "Scout", "Parent"],
    },
  },
  {
    id: "couples",
    name: "Couples Orbit",
    short_name: "Couples",
    description: "Strengthen your relationship with shared goals, date nights, gratitude, and milestones.",
    category: "Relationships",
    theme_id: "family",
    featured: true,
    premium: false,
    version: 1,
    icon: "heart-multiple",
    placeholder: "Our Shared Orbit",
    starter_summary: ["Connection habits", "Date-night rewards", "Shared projects", "Relationship milestones"],
    included: {
      habits: ["Gratitude", "Quality Time", "Shared Goal Progress"],
      rewards: ["Date Night Choice", "Favorite Restaurant Night", "Weekend Adventure", "Special Celebration"],
      projects: ["Shared Goals Kickoff"],
      milestones: ["First date night", "30 days of gratitude", "First shared goal"],
      roles: ["Partner"],
    },
  },
  {
    id: "accountability_circle",
    name: "Accountability Circle",
    short_name: "Accountability Circle",
    description: "Weekly check-ins, shared goals, and group accountability.",
    category: "Accountability",
    theme_id: "default",
    featured: true,
    premium: false,
    version: 1,
    icon: "target",
    placeholder: "Weekly Accountability Circle",
    starter_summary: ["Check-in habits", "Goal tasks", "Group rewards", "Kickoff project"],
    included: {
      habits: ["Daily Check-In", "Goal Progress", "Encouragement"],
      rewards: ["Group Celebration", "Accountability Champion", "Consistency Award"],
      projects: ["First Check-In Setup"],
      milestones: ["First check-in", "Consistency streak", "First group goal"],
      roles: ["Moderator", "Member"],
    },
  },
  {
    id: "fitness_group",
    name: "Fitness Group",
    short_name: "Fitness Group",
    description: "Workouts, step goals, fitness challenges, and team motivation.",
    category: "Health & Fitness",
    theme_id: "fitness",
    featured: true,
    premium: false,
    version: 1,
    icon: "run",
    placeholder: "Morning Fitness Group",
    starter_summary: ["Workout habits", "Fitness challenges", "Progress rewards", "Kickoff project"],
    included: {
      habits: ["Workout", "Stretching", "Hydration"],
      rewards: ["Workout Streak Reward", "Group Celebration", "Fitness Champion"],
      projects: ["Fitness Group Kickoff"],
      milestones: ["First workout", "Workout streak", "Fitness goal completed"],
      roles: ["Coach", "Member"],
    },
  },
  {
    id: "study_group",
    name: "Study Group",
    short_name: "Study Group",
    description: "Study sessions, reading goals, exam prep, and group focus.",
    category: "Learning",
    theme_id: "study",
    featured: false,
    premium: false,
    version: 1,
    icon: "school",
    placeholder: "Exam Prep Study Group",
    starter_summary: ["Study habits", "Prep tasks", "Focus rewards", "Study project"],
    included: {
      habits: ["Reading", "Study Session", "Practice Questions"],
      rewards: ["Study Streak Reward", "Group Celebration", "Focus Champion"],
      projects: ["Study Group Kickoff"],
      milestones: ["First study session", "Reading goal", "Exam prep complete"],
      roles: ["Group Lead", "Member"],
    },
  },
  {
    id: "blank",
    name: "Blank Orbit",
    short_name: "Blank Orbit",
    description: "Start with an empty Orbit and customize everything yourself.",
    category: "Custom",
    theme_id: "default",
    featured: false,
    premium: false,
    version: 1,
    icon: "orbit",
    placeholder: "My Orbit",
    secondary: true,
    starter_summary: ["Private invite-only Orbit", "Choose your own habits", "Customize everything"],
    included: {
      habits: [],
      rewards: [],
      projects: [],
      milestones: [],
      roles: ["Owner", "Member"],
    },
  },
];

export const FEATURED_TEMPLATES = TEMPLATE_CATALOG.filter((template) => template.featured);

export function getTemplateById(id) {
  return TEMPLATE_CATALOG.find((template) => template.id === id) || TEMPLATE_CATALOG[0];
}

export function templateCreateOptions() {
  return TEMPLATE_CATALOG.map((template) => ({
    ...template,
    title: template.name,
    nameSuggestion: template.placeholder,
    highlights: template.starter_summary,
  }));
}

export function onboardingTemplates() {
  return TEMPLATE_CATALOG.map((template) => ({
    ...template,
    title: template.name,
    placeholder: template.placeholder,
    secondary: template.secondary || template.id === "blank",
  }));
}
